### ISSUE TITLE
Error: Unknown authentication strategy \"shopify-1484291442301\"

### ISSUE THREAD

**Issue by somprabhsharma** [danteata/passport-shopify#10]
@danteata @siacomuzzi @niftylettuce @riversy  Hi I get the error Error: Unknown authentication strategy \"shopify-1484291442301\" when I use your strategy on a production server, but it does not happen on localhost or staging server. Can you help me how this can be possible?

**Comment by riversy** [comment]
Hi! 
Is it possible that you use multithread model in your app? 
This might happen then you start authentication from one thread. In this moment shopify-1484291442301 passport created and then server response to callback, it happens in other thread. Other thread doesn't know about shopify-1484291442301, so you'll get error. 
I've recently got the same then used scenario above.

**Comment by somprabhsharma** [comment]
You are absolutely correct. Thank you for prompt reply. You saved my day. 👍

**Comment by somprabhsharma** [comment]
You can close the issue.

**Comment by somprabhsharma** [comment]
@riversy can you suggest how can I use your strategy in a multiple server architecture with a load balancer ?

**Comment by riversy** [comment]
Hi, sorry for delay. 
You need to use sticky strategy. The simplest way is to stick by IP. 
1. In the scope of one node You need to handle on 'connection' event, count worker index by IP and send it to the worker. So the user with one IP will stick to the one worker in the scope of one node. See a piece of code from our project below:

```

  workers = []
  spawn = (i) ->
    workers[i] = cluster.fork()

    workers[i].on 'exit', ->
      console.log "Worker #{i} died."

      # Restart worker if app
      # in production mode
      spawn(i) if process.env.NODE_ENV is 'production'
      return

  spawn i for i in [1..threadCount]

  workerIndex = (ip) ->
    hash(ip) % threadCount + 1

  server = net.createServer pauseOnConnect: true, (connection) ->
    worker = workers[workerIndex(connection.remoteAddress)]
    worker.send 'sticky-session:connection', connection
    return
  .listen config.http_port
```

worker uses following code to handle connection:

```
  process.on 'message', (message, connection) ->
    return if 'sticky-session:connection' isnt message
    server.emit 'connection', connection
    connection.resume()
```

2. And the second thing you need is to ask your balancer (haproxy or nginx) to stick user to the one physical node. We used **haproxy**. So there's a piece of it's config from our project:

```
backend habackend
    mode http
    balance roundrobin
    option forwardfor
    option httpchk HEAD / HTTP/1.1\r\nHost:localhost
    cookie SERVERID insert indirect
    server app1 localhost:9000 cookie app1 check
```

As you can see we used Cookie Strategy to stick user to server. But you can also use IP Based Strategy. There's an article about HAProxy [https://goo.gl/u3XEXv](https://goo.gl/u3XEXv). But I'm sure **nginx** has options. 

Hope this will help you.

**Comment by riversy** [comment]
@somprabhsharma Did it helped? Can you close the issue?
