### ISSUE TITLE
Examples broken since commit d596b08ca7a15d9c21eff5378858db613400b799

### ISSUE THREAD

**Issue by raffpaquin** [danteata/passport-shopify#7]
Hi! Is it possible that the example does not work anymore (since commit d596b08ca7a15d9c21eff5378858db613400b799 I think.)

**Comment by vmdao** [comment]
Not work :(

**Comment by danteata** [comment]
@raffpaquin @vmdao I've pushed an update and the example should work now. Let me know if it doesn't resolve it. Thanks!
